# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd4fbdd7c2367ae85aca1a4311b7effacf2f22cb7310c98cf15174aaf5a6d989560c96790c996efa5a9d418c1f9b5a3ec190a6317eaf8cbc9a558fe8a811a26c

test:
  secret_key_base: b611b67c22ac150f23aa151d3c3e6a3b02be11346688f4f6d6fea2d9b145dd449b9c6c6ad091d607d559fcb55dfa2b6a62dfa5aaf44828be520070a29a264476

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
